SEARCH_KEYWORDS = ["python developer fresher", "data scientist fresher"]
LOCATION = "India"
EXPERIENCE_YEARS = 0
MAX_JOBS_PER_SITE = 50
MIN_SALARY_LPA = 0
YOUR_SKILLS = ["python", "tensorflow", "react"]
CITIES = ["Bangalore", "Mumbai", "Delhi"]
OUTPUT_FILE = "output/jobs_found.json"
EXCEL_FILE = "output/jobs_found.xlsx"
GOVT_SITES = {"ISRO": "https://www.isro.gov.in/Careers.html"}
HEADLESS = True
REQUEST_DELAY = 2
MAX_RETRIES = 3
# Add your keys here:
GITHUB_TOKEN = "your_github_token"
GEMINI_API_KEY = "your_gemini_key"
EMAIL_ID = "your_email@gmail.com"
EMAIL_PASSWORD = "your_app_password"
NOTIFY_EMAIL = EMAIL_ID
