"""Write supabase/seed.sql from data/govt_jobs.json (reviewed records, published)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
jobs = json.loads((ROOT / "data" / "govt_jobs.json").read_text(encoding="utf-8"))["jobs"]
lines = ["-- Generated by scripts/make_seed_sql.py from data/govt_jobs.json. Re-running it is safe.",
         "insert into public.govt_jobs (id, data, published, source_kind) values"]
rows = []
for j in jobs:
    body = json.dumps(j, ensure_ascii=False)
    assert "$seed$" not in body
    rows.append(f"  ('{j['id']}', $seed${body}$seed$::jsonb, true, 'manual')")
lines.append(",\n".join(rows))
lines.append("on conflict (id) do nothing;")
(ROOT / "supabase" / "seed.sql").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote supabase/seed.sql with {len(jobs)} records")
